[project]
name = "the-caddie"
description = "A companion utility for orchestrating LinkML release artifacts."
readme = "README.md"
authors = [
    { name = "Eric Torstenson", email = "eric.s.torstenson@vumc.org" }
]
requires-python = ">=3.10,<3.14"
dependencies = [
    "hatchling>=1.27.0",
    "httpx>=0.28.1",
    "linkml>=1.9.6, <2.0.0",
    "linkml-runtime>=1.9.5, <2.0.0",
    "rich>=15.0.0",
    "ruyaml>=0.91.0",
    "tomli ; python_full_version < '3.11'",
]
dynamic = ["version"]

[build-system]
requires = [
    "hatchling>=1.21.0",
    "hatch-vcs>=0.4.0",
    "setuptools-scm>=8.0.0"
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
# Prevents the long, ugly local commit hashes (+gxxxxxx) from inflating clean tags
local_scheme = "no-local-version"

[tool.hatch.build.targets.wheel]
packages = ["src/caddie"]

[project.entry-points.hatch]
# Format: plugin-alias = "module.path"
caddie-sqla = "caddie.hatch_build"

[project.scripts]
gen-dbtmodel = "caddie.dbtmodel:main"
linkml_extract_dd = "caddie.ftddd.linkml:cli"
gen-monolith = "caddie.gen_monolith:main"
update-cam = "caddie.update_cam:main"
